swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/account:
    post:
      security:
        - Bearer: [ ]
      tags:
        - User Account management
      summary: User Account List
      description: API for fetching user accounts
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Accounts retrieved successfully
          schema:
            type: array
            items:
              $ref: '#/definitions/AccountApiResponse'
        '401':
          description: The token is invalid.
        '403':
          description: Unauthorized access for this role
        '500':
          description: Internal Server Error
  /user/account/{idAccount}/transactions/current-month:
    get:
      security:
        - Bearer: [ ]
      tags:
        - User Account management
      summary: Current month Account Transactions
      description: API for fetching a user account current month transactions.
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: idAccount
          in: path
          description: User ID
          type: integer
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Account transactions retrieved successfully
          schema:
            type: array
            items:
              $ref: '#/definitions/AccountTransactionResponse'
        '401':
          description: The token is invalid.
        '403':
          description: Unauthorized access for this role
        404:
          description: An account with the specified ID was not found.
        '500':
          description: Internal Server Error
  /user/account/{idAccount}/transactions:
    post:
      security:
        - Bearer: [ ]
      tags:
        - User Account management
      summary: Create an Account Transaction
      description: API to create a user transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: idAccount
          in: path
          description: Account ID
          type: integer
          required: true
        - in: body
          name: body
          description: Create account transaction attributes
          required: true
          schema:
            $ref: '#/definitions/AccountCreateTransaction'
      produces:
        - application/json
      responses:
        '200':
          description: Account transaction created successfully
          schema:
            $ref: '#/definitions/AccountUpdateTransactionsResponse'
        '401':
          description: The token is invalid.
        '403':
          description: Unauthorized access for this role
        404:
          description: An Account with the specified ID was not found.
        '500':
          description: Internal Server Error
  /user/transactions/{idTransaction}:
    get:
      security:
        - Bearer: [ ]
      tags:
        - User Account management
      summary: Detail of a Transaction
      description: API to read a user transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: idTransaction
          in: path
          description: Transaction ID
          type: integer
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Account transaction retrieved successfully
          schema:
            $ref: '#/definitions/AccountUpdateTransactionsResponse'
        '401':
          description: The token is invalid.
        '403':
          description: Unauthorized access for this role
        404:
          description: A transaction with the specified ID was not found.
        '500':
          description: Internal Server Error
    patch:
      security:
        - Bearer: [ ]
      tags:
        - User Account management
      summary: Update Account Transaction
      description: API for updating a user transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: idTransaction
          in: path
          description: Transaction ID
          type: integer
          required: true
        - in: body
          name: body
          description: Update account transaction attributes
          required: true
          schema:
            $ref: '#/definitions/AccountUpdateTransactions'
      produces:
        - application/json
      responses:
        '200':
          description: Account transaction updated successfully
          schema:
            $ref: '#/definitions/AccountUpdateTransactionsResponse'
        '401':
          description: The token is invalid.
        '403':
          description: Unauthorized access for this role
        404:
          description: A transaction with the specified ID was not found.
        '500':
          description: Internal Server Error
    delete:
      security:
        - Bearer: [ ]
      tags:
        - User Account management
      summary: Delete an Account Transaction
      description: API to delete a user transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: idTransaction
          in: path
          description: Transaction ID
          type: integer
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Account transaction removed successfully
          schema:
            $ref: '#/definitions/AccountDeleteTransactionResponse'
        '401':
          description: The token is invalid.
        '403':
          description: Unauthorized access for this role
        404:
          description: A Transaction with the specified ID was not found.
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  AccountApiResponse:
    type: object
    properties:
      idAccount:
        type: integer
      description:
        type: string
      label:
        type: string
      balance:
        type: number
  AccountTransactionResponse:
    type: object
    properties:
      idTransaction:
        type: integer
      category:
        type: integer
      transactionType:
        type: integer
      note:
        type: string
      date:
        type: string
      amount:
        type: number
      balance:
        type: number
      description:
        type: string
  AccountUpdateTransactions:
    properties:
      category:
        type: id
        description: The category type of the transaction
      note:
        type: string
        description: The notes to link to the transaction
  AccountUpdateTransactionsResponse:
    type: object
    properties:
      idAccount:
        type: integer
      idTransaction:
        type: integer
      category:
        type: integer
      transactionType:
        type: integer
      note:
        type: string
      date:
        type: string
      amount:
        type: number
      balance:
        type: number
      description:
        type: string
  AccountCreateTransaction:
    properties:
      category:
        type: integer
        description: The category type of the transaction
      note:
        type: string
        description: The notes to link to the transaction
      transactionType:
        type: integer
        description: The id of the transaction type
      date:
        type: string
        description: The date of the transaction
      amount:
        type: number
        description: The transaction's amount
      balance:
        type: number
        description: The transaction's balance
      description:
        type: string
        description: The transaction's description
  AccountCreateTransactionResponse:
    type: object
    properties:
      idAccount:
        type: integer
      idTransaction:
        type: integer
      category:
        type: integer
      transactionType:
        type: integer
      note:
        type: string
      date:
        type: string
      amount:
        type: number
      balance:
        type: number
      description:
        type: string
  AccountDeleteTransactionResponse:
    type: string
    example: "The transaction has been successfully deleted"